version: '2'
services:
  web:
    container_name: devbox-php-nginx
    restart: always
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - /logs/nginx:/var/log/nginx
      - /logs/php:/var/log/php
      - /scripts:/scripts
      - /var/www:/var/www
      - /vagrant:/vagrant

  weba:
    container_name: devbox-php-apache
    restart: always
    build:
          context: .
          dockerfile: DockerfileApache
    ports:
        - ${APACHE_PORT}:80
    volumes:
        - /var/www:/var/www
        - /vagrant:/vagrant
        - /logs/apache2:/var/log/apache2



  mailhog:
    container_name: devbox-mailserver
    restart: always
    image: mailhog/mailhog:v1.0.0
    ports:
      - ${MAILSERVER_SMTP_PORT}:${MAILSERVER_SMTP_PORT}
      - ${MAILSERVER_UI_PORT}:${MAILSERVER_UI_PORT}

  redis:
    container_name: devbox-redis
    restart: always
    image: redis:latest
    links:
      - web
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  blackfire:
    container_name: devbox-blackfire
    image: blackfire/blackfire
    restart: always
    links:
      - web
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
